// ─── 카테고리 순서 ───────────────────────────────────────────────
export const CATEGORY_ORDER = [
  'people', 'composition', 'character', 'hairstyle', 'body', 'Attire',
  'pose', 'fetish', 'action', 'sexual_action', 'accessories'
]


// ─── 서브카테고리 설정 ───────────────────────────────────────────
export const CATEGORY_CONFIG = {
  people: [
    { key: 'people.number_of_people', label: '인원수', multi: false }
  ],
  composition: [
    { key: 'composition.angle', label: '앵글', multi: false },
    { key: 'composition.layout_and_composition', label: '구도', multi: false },
    { key: 'composition.border_layout', label: '테두리', multi: true },
    { key: 'composition.viewer_focus', label: '시선 초점', multi: false },
    { key: 'composition.body_focus', label: '신체 초점', multi: true },
    { key: 'composition.subject_focus', label: '대상 초점', multi: false },
  ],
  character: [
    { key: 'character.race', label: '종족', multi: false },
    { key: 'character.state', label: '상태', multi: true },
    { key: 'character.organization', label: '소속', multi: false },
    { key: 'character.alteration', label: '변형', multi: true },
    { key: 'character.game_character', label: '게임 캐릭터', multi: true },
  ],
  hairstyle: [
    { key: 'hairstyle.combinable.bangs', label: '앞머리', multi: true },
    { key: 'hairstyle.combinable.hair_elements', label: '헤어 요소', multi: true },
    { key: 'hairstyle.combinable.overall_style', label: '전체 스타일', multi: true },
    { key: 'hairstyle.combinable.length', label: '길이', multi: false },
    { key: 'hairstyle.combinable.curl', label: '웨이브', multi: false },
    { key: 'hairstyle.combinable.hair_color', label: '색상', multi: false },
    { key: 'hairstyle.combinable.multicolor', label: '멀티컬러', multi: true },
    { key: 'hairstyle.combinable.side_hair', label: '옆머리', multi: true },
    { key: 'hairstyle.combinable.state', label: '상태', multi: true },
    { key: 'hairstyle.combinable.facial_hair', label: '수염', multi: true },
    { key: 'hairstyle.non_combinable.specific_style', label: '특수 스타일 (단일)', multi: false },
    { key: 'hairstyle.non_combinable.alternate_style', label: '대체 스타일', multi: false },
  ],
  Attire: [
    { key: 'Attire.fabric_and_material', label: '소재', multi: true },
    { key: 'Attire.torn_damaged', label: '손상', multi: true },
    { key: 'Attire.clothing_state', label: '착용 상태', multi: true },
    { key: 'Attire.fashion', label: '패션', multi: true },
    { key: 'Attire.tops', label: '상의', multi: true, exclusiveWith: ['Attire.one_piece'] },
    { key: 'Attire.top_cutout', label: '상의 컷아웃', multi: true },
    { key: 'Attire.bottoms', label: '하의', multi: true, exclusiveWith: ['Attire.one_piece'] },
    { key: 'Attire.bottom_cutout', label: '하의 컷아웃', multi: true },
    { key: 'Attire.one_piece', label: '원피스', multi: false, exclusiveWith: ['Attire.tops', 'Attire.bottoms'] },
    { key: 'Attire.outerwear', label: '아우터', multi: true },
    { key: 'Attire.cape', label: '망토', multi: false },
    { key: 'Attire.armor', label: '갑옷', multi: true },
    { key: 'Attire.uniform', label: '유니폼', multi: false },
    { key: 'Attire.traditional', label: '전통 의상', multi: false },
    { key: 'Attire.sleeve', label: '소매', multi: true },
    { key: 'Attire.pattern_clothes', label: '패턴', multi: true },
    { key: 'Attire.pajamas', label: '파자마', multi: false },
    { key: 'Attire.print_pattern', label: '프린트', multi: true },
    { key: 'Attire.brassiere', label: '브라', multi: false },
    { key: 'Attire.panties', label: '팬티', multi: false },
    { key: 'Attire.lingerie', label: '란제리', multi: false, exclusiveWith: ['Attire.bikinis', 'Attire.one_piece_swimsuit'] },
    { key: 'Attire.bikinis', label: '비키니', multi: true, exclusiveWith: ['Attire.one_piece_swimsuit', 'Attire.lingerie'] },
    { key: 'Attire.one_piece_swimsuit', label: '원피스 수영복', multi: false, exclusiveWith: ['Attire.bikinis', 'Attire.lingerie'] },
    { key: 'Attire.underwear_general', label: '속옷 일반', multi: true },
    { key: 'Attire.legwear', label: '레그웨어', multi: true },
    { key: 'Attire.footwear', label: '신발', multi: false },
    { key: 'Attire.collar_detail', label: '칼라', multi: true },
    { key: 'Attire.cosplay', label: '코스프레', multi: false },
    { key: 'Attire.outfit_change', label: '의상 변경', multi: false },
    { key: 'Attire.apron', label: '앞치마', multi: false },
    { key: 'Attire.sarong', label: '사롱', multi: false },
  ],
  fetish: [
    { key: 'fetish.fluid', label: '체액', multi: true },
    { key: 'fetish.expression_orgasm', label: '오르가즘 표정', multi: true },
    { key: 'fetish.after_sex_state', label: '사후 상태', multi: true },
    { key: 'fetish.bdsm_restraint', label: 'BDSM', multi: true },
    { key: 'fetish.subculture_fetish', label: '서브컬처 페티시', multi: true },
    { key: 'fetish.situation_action', label: '상황/행동', multi: true },
    { key: 'fetish.visual_item', label: '시각적 아이템', multi: true },
    { key: 'fetish.sexual_features', label: '신체 특징', multi: true },
    { key: 'fetish.sexual_positions', label: '체위/자세', multi: true },
    { key: 'fetish.censorship', label: '검열', multi: false },
    { key: 'fetish.nipple_accessory', label: '유두 액세서리', multi: true },
    { key: 'fetish.full_body_nudity', label: '나체', multi: true },
  ],
  pose: [
    { key: 'combinable.head_hair_face', label: '머리/얼굴', multi: true },
    { key: 'combinable.arm_pose', label: '팔 포즈', multi: true },
    { key: 'combinable.hand_gesture', label: '손 제스처', multi: true },
    { key: 'combinable.head_hair_clothing', label: '머리/의상', multi: true },
    { key: 'combinable.clothing_action', label: '의상 동작', multi: true },
    { key: 'non_combinable.full_body_pose', label: '전신 포즈 (단일)', multi: false },
    { key: 'non_combinable.arm_pose', label: '팔 포즈 (단일)', multi: false },
    { key: 'non_combinable.leg_pose', label: '다리 포즈 (단일)', multi: false },
    { key: 'non_combinable.appeal', label: '어필 포즈', multi: true },
    { key: 'non_combinable.action_pose', label: '액션 포즈', multi: true },
  ],
  action: [
    { key: 'action.holding_weapon', label: '무기 들기', multi: true },
    { key: 'action.holding_object_generic', label: '물건 들기', multi: true },
    { key: 'action.holding_flora_animal', label: '생물/꽃 들기', multi: true },
    { key: 'action.holding_everyday_items', label: '일상 아이템', multi: true },
    { key: 'action.body_activity', label: '신체 활동', multi: false },
    { key: 'action.daily_activity', label: '일상 활동', multi: false },
    { key: 'interaction.affection_embrace', label: '애정/포옹', multi: true },
    { key: 'interaction.oral_intimacy', label: '구강 친밀', multi: true },
    { key: 'interaction.communication_expression', label: '소통/표현', multi: true },
    { key: 'interaction.playful_interaction', label: '장난', multi: true },
  ],
  sexual_action: [
    { key: 'sexual_action.insertion_sex', label: '삽입', multi: true },
    { key: 'sexual_action.non_insertion_sex', label: '비삽입', multi: true },
    { key: 'sexual_action.masturbation', label: '자위', multi: true },
    { key: 'sexual_action.group_sex', label: '그룹', multi: true },
    { key: 'sexual_action.special_situations', label: '특수 상황', multi: true },
  ],
  accessories: [
    { key: 'accessory.headwear.hat', label: '모자', multi: false },
    { key: 'accessory.headwear.helmet', label: '헬멧', multi: false },
    { key: 'accessory.headwear.crown', label: '왕관', multi: false },
    { key: 'accessory.headwear.hood', label: '후드', multi: false },
    { key: 'accessory.headwear.headband', label: '헤드밴드', multi: false },
    { key: 'accessory.headwear.veil', label: '베일', multi: false },
    { key: 'accessory.hair_accessory.hair_ornament', label: '헤어 장식', multi: true },
    { key: 'accessory.hair_accessory.hairpin', label: '헤어핀', multi: true },
    { key: 'accessory.hair_accessory.hairband', label: '머리띠', multi: false },
    { key: 'accessory.hair_accessory.hair_tie', label: '머리끈', multi: false },
    { key: 'accessory.eyewear', label: '안경/고글', multi: false },
    { key: 'accessory.earwear', label: '귀걸이', multi: true },
    { key: 'accessory.neckwear.necktie', label: '넥타이', multi: false },
    { key: 'accessory.neckwear.bowtie', label: '나비넥타이', multi: false },
    { key: 'accessory.neckwear.choker', label: '초커', multi: false },
    { key: 'accessory.neckwear.necklace', label: '목걸이', multi: true },
    { key: 'accessory.neckwear.scarf', label: '스카프', multi: false },
    { key: 'accessory.handwear.gloves', label: '장갑', multi: false },
    { key: 'accessory.handwear.ring', label: '반지', multi: true },
    { key: 'accessory.armwear.bracelet', label: '팔찌', multi: true },
    { key: 'accessory.armwear.armband', label: '완장', multi: true },
    { key: 'accessory.bodywear.belt', label: '벨트', multi: false },
    { key: 'accessory.bodywear.harness', label: '하네스', multi: false },
    { key: 'accessory.legwear_accessory.thigh', label: '허벅지 스트랩', multi: true },
    { key: 'accessory.legwear_accessory.garter', label: '가터', multi: false },
    { key: 'accessory.jewelry.general', label: '주얼리', multi: true },
    { key: 'accessory.bag', label: '가방', multi: false },
    { key: 'accessory.misc.ribbon', label: '리본', multi: true },
    { key: 'accessory.mask_costume.mask', label: '마스크', multi: false },
  ],
  body: [
    { key: 'body.body_shape', label: '체형', multi: true },
    { key: 'body.breast_size', label: '가슴 사이즈', multi: false },
    { key: 'body.makeup.eye', label: '아이 메이크업', multi: true },
    { key: 'body.makeup.lip', label: '립', multi: true },
    { key: 'body.makeup.face', label: '페이스', multi: true },
    { key: 'body.nail.hand', label: '손톱', multi: true },
    { key: 'body.facial_hair', label: '수염', multi: true },
    { key: 'body.piercing', label: '피어싱', multi: true },
    { key: 'body.tattoo_marking.motif', label: '문신', multi: true },
    { key: 'body.bandage_injury', label: '붕대/부상', multi: true },
  ],
}